# Custom Language File for Launcher Customizer

[ejs.app]
title = "TerraLuna Launcher - ( 1.0.0 베타버전 )"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "https://github.com/kimoejin1233/TerraLunaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/kimoejin1233/TerraLunaLauncher"
supportLink = "https://github.com/kimoejin1233/TerraLunaLauncher/issues"

[ejs.welcome]
welcomeHeader = "TerraLuna"
welcomeDescription = "TerraLuna는 소소하게 야생을 즐기는 서버입니다. 1인으로 제작되어 만들어진 서버이므로 오류나 서버상태가 가끔 안좋은점을 이해해주시길 바랍니다."
welcomeDescCTA = "즐겁게 즐겨주시고 원하시는게 있으면 알려주시면 감사하겠습니다."
