# Custom Language File for Launcher Customizer

[ejs.app]
title = "TerraLuna Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "TerraLuna 서버에 오신걸 환영합니다~"
welcomeDescription = "TerraLuna 서버는 잔잔하게 지인들과 즐기는 반야생 서버입니다."
welcomeDescCTA = "즐거운 여행 되시길."
