[ejs.landing]
updateAvailableTooltip = "업데이트 가능"
usernamePlaceholder = "유저이름"
usernameEditButton = "설정"
settingsTooltip = "세팅"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "Non&nbsp;비필수"
newsButton = "새로운 시작"
launchButton = "플레이"
launchButtonPlaceholder = "&#8226; 서버를 선택하지 않았습니다."
launchDetails = "잠시만 기다려 주세요..."
newsNavigationStatus = "{currentPage} 중 {totalPages}"
newsErrorLoadSpan = "새로운 버전 확인중..,"
newsErrorFailedSpan = "새로운 버전 로드 실패"
newsErrorRetryButton = "다시 시도해 주세요."
newsErrorNoneSpan = "새로운 버전이 없습니다."

[ejs.login]
loginCancelText = "취소"
loginSubheader = "마인크래프트 로그인"
loginEmailError = "* 잘못된 형식입니다."
loginEmailPlaceholder = "이메일 또는 아이디"
loginPasswordError = "* 비밀번호입력을 해주세요."
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊으셨나요?"
loginRememberMeText = "remember me?"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "계정이 필요하십니까?"
loginPasswordDisclaimer1 = "귀하의 비밀번호는 mojang 으로 직접 전송되며 절대 다른서버로 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName} 프로그램은 Mojang AB의 공식 런쳐가 아닙니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인 옵션"
loginWithMicrosoft = "Microsoft 으로 로그인"
loginWithMojang = "Mojang 으로 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "사용 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "서버를 선택하세요."
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트 설정"
navMods = "모드"
navJava = "자바"
navLauncher = "런쳐"
navAbout = "정보"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "새 계정을 추가하거나 기존 계정을 관리합니다."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Microsoft 계정 추가"
mojangAccount = "Mojang"
addMojangAccount = "+ Mojang 계정 추가"
minecraftTabHeaderText = "마인크래프트 세팅"
minecraftTabHeaderDesc = "게임 출시와 관련된 옵션"
gameResolutionTitle = "게임 해상도"
launchFullscreenTitle = "전체 화면으로 실행"
autoConnectTitle = "시작 시 서버에 자동으로 연결"
launchDetachedTitle = "런처에서 게임 프로세스를 분리합니다."
launchDetachedDesc = "게임이 분리되지 않은 경우 런쳐를 닫으면 게임도 종료됩니다."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드를 활성화하거나 비활성화합니다."
switchServerButton = "교체"
requiredMods = "필수 모드"
optionalMods = "옵션 모드"
dropinMods = "Drop-in Mods"
addMods = "모드 추가"
dropinRefreshNote = "(F5를 눌러 새로고침)"
shaderpacks = "쉐이더팩"
shaderpackDesc = "셰이더를 활성화하거나 비활성화합니다. 셰이더는 강력한 설정에서만 원활하게 실행됩니다. 여기에 커스텀 팩을 추가할 수 있습니다."
selectShaderpack = "셰이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "Java 구성(고급)을 설정합니다."
memoryTitle = "메모리"
maxRAM = "최대 메모리 (본인컴퓨터의 절반 설정)"
minRAM = "최소 메모리"
memoryDesc = "권장 최소메모리는 4GB 입니다. 최소값과 최대값을 동일한 값으로 설정하면 지연이 줄어들 수 있습니다."
memoryTotalTitle = "전체 옹량"
memoryAvailableTitle = "사용 가능한 용량"
javaExecutableTitle = "자바 실행 파일"
javaExecSelDialogTitle = "자바 실행 파일 선택"
javaExecSelButtonText = "파일 선택"
javaExecDesc = "자바 실행 파일은 게임 실행 전에 검증됩니다."
javaPathDesc = "경로는 <strong>{pathSuffix}</strong>로 끝나야 합니다."
jvmOptsTitle = "추가 JVM 옵션"
jvmOptsDesc = "런타임에 JVM에 제공할 옵션. <em>-Xms</em> 및 <em>-Xmx</em>는 포함하지 않아야 합니다."
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처 자체와 관련된 옵션"
allowPrereleaseTitle = "프리릴리즈 업데이트 허용"
allowPrereleaseDesc = "프리릴리즈에는 완전히 테스트되지 않았거나 통합되지 않은 새로운 기능이 포함되어 있습니다.<br>프리릴리즈 버전을 사용하는 경우 항상 참이 됩니다."
dataDirectoryTitle = "데이터 디렉토리"
selectDataDirectory = "데이터 디렉토리 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일 및 로컬 자바 설치는 데이터 디렉토리에 저장됩니다. <br>스크린샷과 월드 저장은 해당 서버 구성의 인스턴스 폴더에 저장됩니다."
aboutTabHeaderText = "정보"
aboutTabHeaderDesc = "현재 버전의 정보 및 변경된 사항을 봅니다."
aboutTitle = "{appName}"
stableRelease = "안정적인 버전"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "지원"
devToolsConsole = "디버그 콘솔"
releaseNotes = "변경 사항"
changelog = "변경 로그"
noReleaseNotes = "변경된 사항이 없습니다."
viewReleaseNotes = "GitHub에서 릴리스 노트 보기"
launcherUpdatesHeaderText = "런처 업데이트"
launcherUpdatesHeaderDesc = "런처의 업데이트를 다운로드, 설치 및 검토합니다."
checkForUpdates = "업데이트 확인"
whatsNew = "새로운 내용"
updateReleaseNotes = "업데이트 릴리스 노트"

[ejs.waiting]
waitingText = "마이크로소프트를 기다리는 중..."

[ejs.welcome]
continueButton = "계속하기"


[js.discord]
waiting = "클라이언트를 기다리는중..."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft 로그인"
microsoftLogoutTitle = "Microsoft 로그아웃"

[js.login]
login = "로그인"
loggingIn = "로그인 중"
success = "성공"
tryAgain = "다시 시도"

[js.login.error]
invalidValue = "* 잘못된 값"
requiredValue = "* 다시시도"

[js.login.error.unknown]
title = "로그인 중 알 수없는 오류"
desc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 확인하세요. (CTRL + Shift + i)"

[js.landing.launch]
pleaseWait = "잠시만 기다려주세요..."
failureTitle = "실행 중 오류"
failureText = "자세한 내용은 콘솔을 확인하세요. (CTRL + Shift + i)"
okay = "확인"

[js.landing.selectedAccount]
noAccountSelected = "선택된 계정이 없습니다."

[js.landing.selectedServer]
noSelection = "선택된 서버가 없습니다."
loading = "로딩중..."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보 확인 중..."
noCompatibleJava = "호환 가능한<br>자바 설치가 없습니다"
installJavaMessage = "마인크래프트를 실행하려면 64비트 자바 {major} 설치가 필요합니다. 복사본을 설치해도 될까요?"
installJava = "자바 설치"
installJavaManually = "수동으로 설치"
javaDownloadPrepare = "자바 다운로드 준비 중.."
javaDownloadFailureTitle = "자바 다운로드 중 오류"
javaDownloadFailureText = "자세한 내용은 콘솔을 확인하세요. (CTRL + Shift + i)"
javaRequired = "실행하려면<br>자바가 필요합니다"
javaRequiredMessage = '마인크래프트를 실행하려면 유효한 x64 자바 {major} 설치가 필요합니다.<br><br>자바를 수동으로 설치하는 방법은 디스코드 자바 관리 가이드</a>를 참조하세요.'
javaRequiredDismiss = "알겠습니다"
javaRequiredCancel = "뒤로 가기"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 배포판을 찾지 못했습니다."
javaDownloadCorruptedError = "다운로드된 JDK의 해시가 잘못되어 파일이 손상되었을 수 있습니다."
extractingJava = "자바 추출 중..."
javaInstalled = "자바 설치 완료!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보 로딩 중..."
fatalError = "치명적인 오류"
unableToLoadDistributionIndex = "배포 인덱스 복사를 로드할 수 없습니다. 자세한 내용은 콘솔을 확인하세요 (CTRL + Shift + i)"
pleaseWait = "잠시만 기다려주세요..."
errorDuringLaunchTitle = "실행 중 오류"
seeConsoleForDetails = "자세한 내용은 콘솔을 확인하세요. (CTRL + Shift + i)"
validatingFileIntegrity = "파일 무결성 검증 중..."
errorDuringFileVerificationTitle = "파일 검증 중 오류"
downloadingFiles = "파일 다운로드 중...."
errorDuringFileDownloadTitle = "파일 다운로드 중 오류"
preparingToLaunch = "실행 준비 중..."
launchingGame = "게임 실행 중..."
launchWrapperNotDownloaded = "주 파일인 LaunchWrapper가 제대로 다운로드되지 않았습니다. 이로 인해 게임이 실행되지 않습니다.<br><br>이 문제를 해결하려면 안티바이러스 소프트웨어를 일시적으로 끄고 게임을 다시 실행하세요.<br><br>계속문제 발생시 디스코드로 문제를 제출하세요</a> 그리고 어떤 안티바이러스 소프트웨어를 사용하는지 알려주세요. 저희가 연락하여 문제를 해결하도록 하겠습니다"
doneEnjoyServer = "완료. 즐서운 여행 되시길."
checkConsoleForDetails = "자세한 내용은 콘솔을 확인하세요. (CTRL + Shift + i)"

[js.landing.news]
checking = "새로운 소식 확인 중"

[js.landing.discord]
loading = "게임 로딩중..."
joining = "TerraLuna로 여행 준비중!"
joined = "TerraLuna 탐험 중!"

[js.overlay]
dismiss = "닫기"

[js.settings.fileSelectors]
executables = "실행파일"
allFiles = "모든 파일"

[js.settings.mstfLogin]
errorTitle = "문제가 발생했습니다."
errorMessage = "Microsoft 인증에 실패했습니다 다시 시도해 주세요."
okButton = "확인"

[js.settings.mstfLogout]
errorTitle = "문제가 발생했습니다."
errorMessage = "Microsoft 로그아웃에 실패했습니다 다시 시도해 주세요."
okButton = "확인"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "계정 선택 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "경고<br>마지막 계정입니다"
lastAccountWarningMessage = "런처를 사용하려면 적어도 하나의 계정에 로그인해야 합니다. 로그아웃한 후 다시 로그인해야 합니다.<br><br>로그아웃하시겠습니까?"
confirmButton = "확인"
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "사용자이름"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "선택된 계정 ✓"
logout = "로그 아웃"

[js.settings.dropinMods]
removeButton = "제거"
deleteFailedTitle = "삭제 실패<br>드롭인 모드 {fullName}"
deleteFailedMessage = "파일이 사용 중이지 않은지 확인하고 다시 시도하세요."
failedToggleTitle = "토글 실패<br>하나 이상의 드롭인 모드"
okButton = "확인"

[js.settings.serverListing]
mainServer = "메인 서버"

[js.settings.java]
selectedJava = "선택됨: Java {version} ({vendor})"
invalidSelection = "잘못된 선택"
requiresJava = "Java {major} x64가 필요합니다."
availableOptions = "Java {major}에 대한 사용 가능한 옵션 (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "사전 출시"
stableReleaseTitle = "안정적인 출시"
releaseNotesFailed = "릴리스 노트를 로드하는 데 실패했습니다."

[js.settings.updates]
newReleaseTitle = "새 릴리스 사용 가능"
newPreReleaseTitle = "새 사전 출시 사용 가능"
downloadingButton = "다운로드 중.."
downloadButton = 'GitHub에서 다운로드<span style="font-size: 10px;color: gray;text-shadow: none !important;">런처를 닫고 dmg를 실행하여 업데이트하세요.</span>'
latestVersionTitle = "최신 버전을 실행하고 있습니다"
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "업데이트 확인 중.."

[js.settings.msftLogin]
errorTitle = "Microsoft 로그인 실패"
errorMessage = "Microsoft 계정을 인증할 수 없습니다. 다시 시도해 주세요."
okButton = "확인"

[js.uibinder.startup]
fatalErrorTitle = "치명적인 오류: 배포 인덱스를 로드할 수 없음"
fatalErrorMessage = "서버에 연결할 수 없어 배포 인덱스를 다운로드할 수 없습니다. 로드할 로컬 사본이 없습니다. <br><br>배포 인덱스는 최신 서버 정보를 제공하는 필수 파일입니다. 이를 없이 런처를 시작할 수 없습니다. 인터넷에 연결되어 있고 애플리케이션을 다시 실행하세요."
closeButton = "닫기"

[js.uibinder.validateAccount]
failedMessageTitle = "로그인 새로 고침 실패"
failedMessage = "<strong>{account}</strong>의 로그인을 새로 고칠 수 없습니다. 다른 계정을 선택하거나 다시 로그인하세요."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>의 로그인을 새로 고칠 수 없습니다. 다시 로그인하세요."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "업데이트 확인 중..."
installNowButton = "지금 설치"
checkForUpdatesButton = "업데이트 확인"

[js.auth.microsoft.error]
noProfileTitle = "로그인 중 오류:<br>프로필이 설정되지 않음"
noProfileDesc = "Microsoft 계정에 아직 Minecraft 프로필이 설정되지 않았습니다. 최근에 게임을 구매했거나 Xbox Game Pass를 통해 이를 사용한 경우, <a href=\"https://minecraft.net/\">Minecraft.net</a>에서 프로필을 설정해야 합니다.<br><br>게임을 아직 구매하지 않은 경우, <a href=\"https://minecraft.net/\">Minecraft.net</a>에서 구매할 수 있습니다."
noXboxAccountTitle = "로그인 중 오류:<br>Xbox 계정 없음"
noXboxAccountDesc = "Microsoft 계정에 연결된 Xbox 계정이 없습니다."
xblBannedTitle = "로그인 중 오류:<br>Xbox Live 사용 불가"
xblBannedDesc = "귀하의 Microsoft 계정은 Xbox Live가 사용할 수 없는 국가에서 생성되었거나 차단되었습니다."
under18Title = "로그인 중 오류:<br>부모 승인 필요"
under18Desc = "18세 미만 사용자의 계정은 성인이 가족에 추가해야 합니다."
unknownTitle = "로그인 중 알 수 없는 오류"
unknownDesc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 참조하세요."

[js.auth.mojang.error]
methodNotAllowedTitle = "내부 오류:<br>허용되지 않는 방법"
methodNotAllowedDesc = "허용되지 않는 방법입니다. 이 오류를 보고해 주세요."
notFoundTitle = "내부 오류:<br>찾을 수 없음"
notFoundDesc = "인증 엔드포인트를 찾을 수 없습니다. 이 문제를 보고해 주세요."
accountMigratedTitle = "로그인 중 오류:<br>계정이 마이그레이션됨"
accountMigratedDesc = "마이그레이션된 계정으로 로그인하려고 했습니다. 사용자 이름으로 계정 이메일을 사용하여 다시 시도하세요."
invalidCredentialsTitle = "로그인 중 오류:<br>잘못된 자격 증명"
invalidCredentialsDesc = "입력한 이메일이나 비밀번호가 올바르지 않습니다. 다시 시도하세요."
tooManyAttemptsTitle = "로그인 중 오류:<br>시도 횟수 초과"
tooManyAttemptsDesc = "최근 이 계정으로 너무 많은 로그인 시도가 있었습니다. 나중에 다시 시도하세요."
invalidTokenTitle = "로그인 중 오류:<br>잘못된 토큰"
invalidTokenDesc = "제공된 접근 토큰이 잘못되었습니다."
tokenHasProfileTitle = "로그인 중 오류:<br>토큰에 프로필이 있음"
tokenHasProfileDesc = "접근 토큰에 이미 프로필이 할당되어 있습니다. 프로필 선택은 아직 구현되지 않았습니다."
credentialsMissingTitle = "로그인 중 오류:<br>자격 증명 누락"
credentialsMissingDesc = "사용자 이름/비밀번호가 제출되지 않았거나 비밀번호가 3자 미만입니다."
invalidSaltVersionTitle = "로그인 중 오류:<br>잘못된 소금 버전"
invalidSaltVersionDesc = "잘못된 소금 버전입니다."
unsupportedMediaTypeTitle = "내부 오류:<br>지원되지 않는 미디어 유형"
unsupportedMediaTypeDesc = "지원되지 않는 미디어 유형입니다. 이 오류를 보고해 주세요."
accountGoneTitle = "로그인 중 오류:<br>계정이 마이그레이션됨"
accountGoneDesc = "계정이 Microsoft 계정으로 마이그레이션되었습니다. Microsoft로 로그인하세요."
unreachableTitle = "로그인 중 오류:<br>접근 불가"
unreachableDesc = "인증 서버에 접근할 수 없습니다. 서버가 온라인인지 확인하고 인터넷에 연결되어 있는지 확인하세요."
gameNotPurchasedTitle = "로그인 중 오류:<br>게임 미구매"
gameNotPurchasedDesc = "로그인하려는 계정이 Minecraft 사본을 구매하지 않았습니다. <a href=\"https://minecraft.net/\">Minecraft.net</a>에서 구매할 수 있습니다."
unknownErrorTitle = "로그인 중 알 수 없는 오류"
unknownErrorDesc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 참조하세요."
